Repository Vaibhav13kamat/My_portfolio, pull requests merged in 2022-10, with the labels that each got.

#4 Updated README.md
  README.md
Labels: hacktoberfest, hacktoberfest-accepted

#8 Add Skills section
  index.html
Labels: hacktoberfest, hacktoberfest-accepted

#12 Updated CSS Style Sheet
  styles/styles.css
Labels: hacktoberfest, hacktoberfest-accepted

#14 Added Footer
  index.html
Labels: hacktoberfest, hacktoberfest-accepted

#15 Adding favicon
  images/favicon.ico
  index.html
Labels: hacktoberfest, hacktoberfest-accepted

#18 updated heading
  .vscode/settings.json
  index.html
  styles/styles.css
Labels: hacktoberfest, hacktoberfest-accepted

#21 corrected grammar on issue #20
  index.html
Labels: hacktoberfest, hacktoberfest-accepted

#19 made intro attractive with typing animation
  index.html
  styles/styles.css
Labels: hacktoberfest, hacktoberfest-accepted

#17 Edited skills section
  index.html
  styles/styles.css
Labels: hacktoberfest, hacktoberfest-accepted

#24 Improving-landing-page
  app.js
  images/bgimage.jpg
  images/profile.png
  index.html
  styles/_media.scss
  styles/style.css
  styles/styles.css
  styles/styles.css.map
  styles/styles.scss
Labels: hacktoberfest, hacktoberfest-accepted

#30 updated readme.md
  README.md
Labels: hacktoberfest, hacktoberfest-accepted

#34 added footer
  images/github.svg
  images/instagram.svg
  images/linkedin.svg
  images/twitter.svg
  index.html
  styles/style.css
Labels: hacktoberfest, hacktoberfest-accepted

#39 updated css
  styles/style.css
Labels: hacktoberfest, hacktoberfest-accepted

#47 Added twitter link
  index.html
Labels: hacktoberfest, hacktoberfest-accepted

#43 Removed pointer cursor on skills hover
  styles/style.css
Labels: hacktoberfest, hacktoberfest-accepted

#44 Removed home from navbar Because it violated DRY principle
  index.html
Labels: hacktoberfest, hacktoberfest-accepted

#55 Fixed transition effect of the skills section
  styles/style.css
Labels: hacktoberfest, hacktoberfest-accepted

#57 Contact Issue Resolved #Issue56
  index.html
Labels: hacktoberfest, hacktoberfest-accepted

#60 added favicon
  images/favicon.png
  index.html
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#69 custom cursor added
  app.js
  index.html
  styles/style.css
Labels: hacktoberfest, hacktoberfest-accepted

#65 Toggle dark mode
  app.js
  index.html
Labels: hacktoberfest, hacktoberfest-accepted

#66 Add issue Template
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: hacktoberfest, hacktoberfest-accepted

#67 fix overlap issue
  styles/style.css
Labels: hacktoberfest, hacktoberfest-accepted

#73 SakshArora
  index.html
  styles/style.css
Labels: question

#76 added underline hover effect on icons
  styles/style.css
Labels: hacktoberfest, hacktoberfest-accepted
